### ISSUE TITLE
Ranking the structures, for instance for virtual screening / docking

### ISSUE THREAD

**Issue by maxlevesque** [thorn-lab/coronavirus_structural_task_force#14]
Once again thank you for your hard work.

My team and I (14 people) would like to use your curated pdb files for a virtual screening of small molecules in the 3CLpro. Then comes the choice of which structure to use among all those you curated.

In my opinion, it would be very useful if you could give a ranking of the structures for a given protein.

I hope that makes any sense to you and once again thank you for your hard work

**Comment by maxlevesque** [comment]
Many thanks for taking the time to answering me, and thanks for the wise warning. Indeed, I am as interested in the measures / statistics you consider are important, as in the final ranking that will for sure depend on the use-case.

--- original message ---
On April 6, 2020, 10:45 PM GMT+2 notifications@github.com wrote:



Hi Max,

we are working on that as also on some more documentation. We will do in the upcoming days some ranking according to different statistics, but please beware that your actual needs may vary depending on the kind of modeling you are trying to do.

—

You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by thorn-lab** [comment]
Hi Max, I am not sure why my answer from two days ago does not show up here. Did you get it?
It was:
"Dear Maximilien,
we will give some guidance about that next week on the homepage insidecorona.net (when it is actually online)! Keep in touch!
Best wishes

Andrea."

**Comment by thorn-lab** [comment]
I would also like to remark that ranking doesn't cut it. It's more complicated than that...

**Comment by maxlevesque** [comment]
Hi Andrea, Your answer did not show up. Anyway sincerely thanks.
I love the complexity of things, and knowing your measures and criteria is as important if not more than the final ranking. Thanks for your hard work! I did not meant to disturb. 🙇
Best wishes
Max

**Comment by thorn-lab** [comment]
You are very welcome! It's for labs like yours that we do this. If you would like to chat towards the end of the week, when the homepage is online, you can find my email in the readme!

**Comment by gsantoni** [comment]
Structures sorted by quality are now available in the utils section. Will keep the issue open for now until presentation is more clear.
Users can query the stats.db file to sort differently (e.g. mx by resolution)

**Comment by maxlevesque** [comment]
Great! 🚀 Thanks!
Could you please consider generating a xlsx or equivalent version of stats.db? 🙏

**Comment by gsantoni** [comment]
Will generate csv of the stats.db and close the issue afterwards.
