### ISSUE TITLE
deadlink

### ISSUE THREAD

**Issue by ksaadDE** [thorn-lab/coronavirus_structural_task_force#172]
https://web.archive.org/web/20201021191805/https://www.uni-wuerzburg.de/en/rvz/research/associated-research-groups/thorn-group/

Siehe Verlinkung zu 171.

Eine Empfehlung: alle Links mit Webarchiv machen, dann habt Ihr das Problem künftig nicht mehr. BG

**Comment by YunyunGao** [comment]
Hi @ksaadDE 
Vielen Dank für Ihr Problem-Ticket. Unsere Gruppe ist an die Universität Hamburg umgezogen. Der Link wurde korrigiert.
