### ISSUE TITLE
6vww/6w01 structures

### ISSUE THREAD

**Issue by jeeberhardt** [thorn-lab/coronavirus_structural_task_force#29]
Hi everyone,

If I am not mistaken, I think that the `6vww` structure (nsp15, https://www.rcsb.org/structure/6vww), currently in `pdb/exonuclease/SARS-CoV-2`, was misplaced as a nsp10-14 protein and should be move to `pdb/endornase/SARS-CoV2` instead with `6wlc`.

For for the `6w01` structure (nsp15, https://www.rcsb.org/structure/6WLC), it seems that it should belong to the `pdb/endornase/SARS-CoV-2` and not `pdb/endornase/SARS-CoV`.

Thanks for your awesome work, very useful!

Jerome.

**Comment by KNolte19** [comment]
Hey Jerome,
you are absolutly right and we fixed the mistake. Thank you for the feedback it is greatly appreciated. 

Kristopher
